# Generated by Django 3.0.5 on 2020-05-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissions', '0002_auto_20200514_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
    ]
