# Generated by Django 3.0.5 on 2020-05-14 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissions', '0003_remove_customuser_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False, help_text='If disabled, this role will be removed from all users.', verbose_name='status')),
                ('desk_access', models.BooleanField(default=True, help_text='Designates whether the Role can have module access.', verbose_name='desk access')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
