# Generated by Django 3.0.5 on 2020-05-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspermissions', '0004_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='created_by',
        ),
    ]
